name: Build Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    if: |
      github.ref == 'refs/heads/dev' ||
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - puppet-chromium-nodejs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.path }}
        push: true
        tags: |
          ghcr.io/DavidKk/${{ matrix.path }}:${{ github.ref == 'refs/heads/dev' && 'alpha' || github.ref == 'refs/tags/' && github.ref_name || 'latest' }}
          ghcr.io/DavidKk/${{ matrix.path }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
