name: Build Docker Images

on:
  push:
    paths:
      - '**/Dockerfile'
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to the Dockerfile'
        required: true
        default: 'puppet-chromium-nodejs'

jobs:
  build:
    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - ${{ github.event.inputs.path || 'puppet-chromium-nodejs' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.path }}
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: |
          ghcr.io/davidkk/${{ matrix.path }}:${{ github.ref == 'refs/heads/dev' && 'alpha' || github.ref == 'refs/tags/' && github.ref_name || 'latest' }}
          ${{ github.ref == 'refs/tags/' && 'ghcr.io/davidkk/${{ matrix.path }}:latest' }}
